name: virbot
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - prodigal # for virbot
  - hmmer # for virbot
  - diamond # for virbot
  - pip:
    - git+https://github.com/rmcolq/RNA_virus_detector.git@dev
