name: scylla
channels:
  - bioconda
  - conda-forge
  - defaults
  - nanoporetech
dependencies:
  - python<=3.10
  - pysam
  - pip
  - kraken2
  - kraken2-server # not on mac
  - fastcat
  - taxonkit
  - fastp
  - tabix
  - mako
  - jq