name: scylla
channels:
  - bioconda
  - conda-forge
  - defaults
  - nanoporetech
dependencies:
  - python<=3.10
  - pysam
  - pip
  - kraken2
  - kraken2-server>=0.1.8 # not on mac
  - fastcat=1.0.1
  - taxonkit
  - fastp=1.3.6
  - tabix
  - mako
  - jq=1.8.2
  - crabz